module.exports = {
  version: '0.1',
  language: 'en',
  minWordLength: 4,
  words: [
    'commitlint',
    'dcloudio',
    'pinia',
    'stylelintrc',
    'stylelintignore',
    'longpress',
    'mediatype',
  ],
  ignorePaths: [
    '**/*.svg',
    '**/*.sh',
    '**/*.conf',
    '**/*.png',
    '**/*.json',
    '**/*.lock',
    '**/*.ttf',
    '**/*.otf',
    '**/*.woff',
    '**/*.ogg',
    '**/*.yml',
    '**/*.yaml',
    'README.md',
    '.gitignore',
    '.prettierrc',
    '.prettierignore',
    '.eslintrc.js',
    '.eslintignore',
    '.stylelintrc.js',
    '.stylelintignore',
  ],
};
